"""Legal knowledge repository port — durable sync/proposals/eval metadata."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from payroll_copilot.application.dto.legal_knowledge import (
    EvaluationCaseResult,
    EvaluationRun,
    LegalChangeProposal,
    LegalSyncRun,
    ProposalStatus,
    VectorIndexHealth,
)


@runtime_checkable
class LegalKnowledgeRepository(Protocol):
    def save_sync_run(self, run: LegalSyncRun) -> LegalSyncRun: ...

    def list_sync_runs(self, *, limit: int = 50) -> list[LegalSyncRun]: ...

    def get_sync_run(self, run_id: str) -> LegalSyncRun | None: ...

    def save_proposal(self, proposal: LegalChangeProposal) -> LegalChangeProposal: ...

    def list_proposals(
        self, *, status: ProposalStatus | None = None, limit: int = 100
    ) -> list[LegalChangeProposal]: ...

    def get_proposal(self, proposal_id: str) -> LegalChangeProposal | None: ...

    def save_snapshot(self, *, source_id: str, content: str, content_hash: str) -> str: ...

    def get_source_state(self, source_id: str) -> dict: ...

    def read_snapshot(self, snapshot_id: str) -> str | None: ...

    def remember_discovery_item(self, item_key: str, content_hash: str) -> None: ...

    def discovery_seen(self, item_key: str, content_hash: str) -> bool: ...

    def save_evaluation_run(self, run: EvaluationRun) -> EvaluationRun: ...

    def list_evaluation_runs(self, *, limit: int = 50) -> list[EvaluationRun]: ...

    def get_evaluation_run(self, run_id: str) -> EvaluationRun | None: ...

    def save_evaluation_cases(self, run_id: str, cases: list[EvaluationCaseResult]) -> None: ...

    def list_evaluation_cases(self, run_id: str) -> list[EvaluationCaseResult]: ...

    def get_active_eval_lock(self) -> str | None: ...

    def acquire_eval_lock(self, run_id: str) -> bool: ...

    def release_eval_lock(self) -> None: ...

    def vector_health(self) -> VectorIndexHealth: ...

    def set_vector_error(self, message: str) -> None: ...

    def set_vector_health(self, health: VectorIndexHealth) -> None: ...
